# Generated by Django 3.1.5 on 2021-02-01 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_1_id', models.IntegerField()),
                ('field_1', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Table_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_1_id', models.IntegerField()),
                ('field_1', models.CharField(max_length=255)),
                ('table_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.table_2')),
            ],
        ),
    ]
