# Generated by Django 3.1.5 on 2021-02-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0002_auto_20210201_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table_2',
            old_name='field_1',
            new_name='field_2',
        ),
    ]
